# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

version: "2"

linters:
  enable:
    # (TODO) uncomment after fixing the lint issues
    # - gofmt
    - govet
    # - unconvert
    # - staticcheck
    # - ineffassign
    # - unparam
    - forbidigo

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

run:
  timeout: 10m
  concurrency: 4
